version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  be: #name of the second service
    build: api-express # specify the directory of the Dockerfile
    image: xebia_be
    ports:
      - "3000:3000" #specify ports forewarding
networks: 
  default:
    external:
      name: backend # create new network if not available ( docker create network backend)