version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  be: #name of the second service
    environment:
        - DOCKER_COMPOSE_DB_SERVICE=db  # exclusively set only in docker-compose 
    build:
      context: api-express # specify the directory of the Dockerfile
      args:
        - configuration=production
        - buildOutputDir=./dist
        - sourceDir=./src
        - sample=defaultsample
    image: konarpriyanku/xebia_be
    ports:
      - "3000:3000" #specify ports forewarding
networks: 
  default:
    external:
      name: backend # create new network if not available ( docker create network backend)