version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  express: #name of the second service
    build: api-express # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
