#!groovy

pipeline{
    agent any
    options{
         buildDiscarder(logRotator(numToKeepStr: '10'))
    }
    environment {
        SRC_DIR='api-express'
        DTR_URL = 'mandeepmehra'
	DTR_CREDS = 'dockerhub'
        DTR_NAMESPACE = 'ge-poc'
        IMAGE_NAME = 'ge-api-poc'
        IMAGE_TAG = "${DTR_URL}/${IMAGE_NAME}:${BUILD_NUMBER}"
    }
    stages{
        stage ('Pull dependencies'){
            steps{
                // download all the necessary packages
                dir("${SRC_DIR}"){
                  sh 'npm install'
                }
            }
        }

        stage ('Unit Testing'){
            steps{
                // download all the necessary packages
                dir("${SRC_DIR}"){
                 sh 'npm test'
                }
            }
        }

        stage ('Build Image'){
            steps{
		dir("${SRC_DIR}"){
    		  script {
		    docker.build IMAGE_TAG + ":$BUILD_NUMBER"
                    // sh "docker build . -t ${IMAGE_TAG}"
		  }
                }
            }
        }
        stage ('Publish Image'){
            steps{
                sh 'echo TBD'
            }
        }

        stage ('Deploy to QA'){
            steps{
                 sh 'echo TBD'
            }
        }

        stage ('Run Integration Tests'){
            steps{
                sh 'echo TBD'
            }
        }
    }
}
